name: Docker Build & Push Laravel Project

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    name: Build and Run Laravel Docker Container
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (required for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-build-

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t laravel-app:latest .

      # Step 5: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d --name laravel-container laravel-app:latest

      # Step 6: Check logs and stop container after running
      - name: Check container logs and clean up
        run: |
          sleep 10  # Adjust if needed
          docker logs laravel-container
          docker stop laravel-container
          docker rm laravel-container
