name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up PHP
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Use the correct PHP version
        extensions: mbstring, pdo, sqlite

    # Step 2: Check out the repository
    - uses: actions/checkout@v3

    # Step 3: Copy the .env file
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: composer install

    # Step 5: Generate application key
    - name: Generate Application Key
      run: php artisan key:generate

    # Step 6: Fix directory permissions
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Step 7: Create SQLite database
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # Step 8: Run PHPUnit or Pest tests
    - name: Execute Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
